In [1]:
from pandas import read_csv
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import grangercausalitytests
from numpy import log
import numpy as np
import pandas as pd
import datetime as datetime

def zscore(df, col):
    col_mean = df[col].rolling(window=10).mean()
    col_std = df[col].rolling(window=10).std()
    return (df[col] - col_mean)/col_std

df = pd.read_csv('./data/11-8/to_trump_2M_dates_res/daily_plutchik_onehot.csv', parse_dates=['month/day'])
approval_rating_df = pd.read_csv('./data/approval_polllist.csv', parse_dates=["enddate"])

df["Anticipation Z-Score"] = zscore(df, "Anticipation")
df["Trust Z-Score"] = zscore(df, "Trust")
df["Surprise Z-Score"] = zscore(df, "Surprise")
df["Sadness Z-Score"] = zscore(df, "Sadness")
df["Joy Z-Score"] = zscore(df, "Joy")
df["Fear Z-Score"] = zscore(df, "Fear")
df["Disgust Z-Score"] = zscore(df, "Disgust")
df["Anger Z-Score"] = zscore(df, "Anger")

start_date = datetime.datetime(2017, 5, 15, 0, 0)
end_date = datetime.datetime(2017, 11, 17, 0, 0)

truncated_df = df[(df["month/day"] > start_date) & (df["month/day"] < end_date)]

In [2]:
result = adfuller(truncated_df["Anticipation Z-Score"])

In [3]:
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -11.027296
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [4]:
result = adfuller(truncated_df["Trust Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -11.493683
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [5]:
result = adfuller(truncated_df["Surprise Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -9.866922
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [6]:
result = adfuller(truncated_df["Sadness Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -11.540513
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [7]:
result = adfuller(truncated_df["Joy Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -9.548665
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [8]:
result = adfuller(truncated_df["Fear Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -8.870502
p-value: 0.000000
	1%: -3.467
	5%: -2.878
	10%: -2.575


In [9]:
result = adfuller(truncated_df["Disgust Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -9.839633
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [10]:
result = adfuller(truncated_df["Anger Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -6.274008
p-value: 0.000000
	1%: -3.467
	5%: -2.878
	10%: -2.575


In [11]:
# p-value is <= 0.05 and ADF Statistic is < values at 1%, 5%, and 10%

In [12]:
truncated_approvals = approval_rating_df.loc[approval_rating_df['pollster'] == 'Gallup']
truncated_approvals = truncated_approvals.loc[truncated_approvals['subgroup'] == 'All polls']
truncated_approvals = truncated_approvals[(truncated_approvals['enddate'] > start_date) & (truncated_approvals['enddate'] <= end_date)]
truncated_approvals = truncated_approvals['adjusted_approve']

approvals_array = truncated_approvals.values

In [15]:
x = np.asarray([approvals_array, truncated_df["Anticipation Z-Score"]]).T

In [16]:
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=2.4484  , p=0.1194  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=2.4892  , p=0.1146  , df=1
likelihood ratio test: chi2=2.4724  , p=0.1159  , df=1
parameter F test:         F=2.4484  , p=0.1194  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.2479  , p=0.2896  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=2.5663  , p=0.2772  , df=2
likelihood ratio test: chi2=2.5484  , p=0.2797  , df=2
parameter F test:         F=1.2479  , p=0.2896  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.1339  , p=0.3369  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=3.5385  , p=0.3158  , df=3
likelihood ratio test: chi2=3.5044  , p=0.3202  , df=3
parameter F test:         F=1.1339  , p=0.3369  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.8377  , p=0.5030  

{1: ({'lrtest': (2.4724119436507408, 0.11586001175149435, 1),
   'params_ftest': (2.4483827315542994, 0.11940239177003237, 180.0, 1.0),
   'ssr_chi2test': (2.4891891104137573, 0.11463077171933894, 1),
   'ssr_ftest': (2.4483827315545152, 0.11940239177001544, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (2.5484214543347434, 0.27965160255210747, 2),
   'params_ftest': (1.2479214435659167, 0.28961438783346055, 177.0, 2.0),
   'ssr_chi2test': (2.5663469234917899, 0.27715635827374768, 2),
   'ssr_ftest': (1.2479214435660626, 0.28961438783341797, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (3.5043861936401299, 0.32019369161467426, 3),
   'params_ftest': (1.1338938624927699, 0.3368655840817732, 174.0, 3.0),
   'ssr_chi2test': (3.5385308467448442, 0.31579907583456845, 3),
   'ssr_ftest': (1.133893862492823, 0.33686558408175499, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  1

In [18]:
x = np.asarray([approvals_array, truncated_df["Trust Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.5014  , p=0.2221  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=1.5264  , p=0.2167  , df=1
likelihood ratio test: chi2=1.5201  , p=0.2176  , df=1
parameter F test:         F=1.5014  , p=0.2221  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.8637  , p=0.4234  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=1.7762  , p=0.4114  , df=2
likelihood ratio test: chi2=1.7676  , p=0.4132  , df=2
parameter F test:         F=0.8637  , p=0.4234  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.2445  , p=0.2952  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=3.8836  , p=0.2743  , df=3
likelihood ratio test: chi2=3.8425  , p=0.2790  , df=3
parameter F test:         F=1.2445  , p=0.2952  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.2263  , p=0.3015  

{1: ({'lrtest': (1.5200738592932339, 0.2176083164765979, 1),
   'params_ftest': (1.5013815318864223, 0.22205980828483762, 180.0, 1.0),
   'ssr_chi2test': (1.5264045574178895, 0.21665285962705574, 1),
   'ssr_ftest': (1.5013815318864485, 0.22205980828483299, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (1.7675559242624104, 0.41321883392218928, 2),
   'params_ftest': (0.8636855496448852, 0.42337441576718771, 177.0, 2.0),
   'ssr_chi2test': (1.7761668930551118, 0.41144355114899511, 2),
   'ssr_ftest': (0.86368554964493083, 0.42337441576716661, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (3.8425081089505966, 0.27898029089049531, 3),
   'params_ftest': (1.2444637668378806, 0.29519471322823948, 174.0, 3.0),
   'ssr_chi2test': (3.8835852034080478, 0.27431232143154671, 3),
   'ssr_ftest': (1.2444637668379379, 0.29519471322821816, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., 

In [19]:
x = np.asarray([approvals_array, truncated_df["Surprise Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=5.1069  , p=0.0250  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=5.1920  , p=0.0227  , df=1
likelihood ratio test: chi2=5.1197  , p=0.0237  , df=1
parameter F test:         F=5.1069  , p=0.0250  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.9959  , p=0.0525  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=6.1610  , p=0.0459  , df=2
likelihood ratio test: chi2=6.0591  , p=0.0483  , df=2
parameter F test:         F=2.9959  , p=0.0525  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.3628  , p=0.0729  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=7.3735  , p=0.0609  , df=3
likelihood ratio test: chi2=7.2272  , p=0.0650  , df=3
parameter F test:         F=2.3628  , p=0.0729  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.1403  , p=0.0779  

{1: ({'lrtest': (5.1197149424788222, 0.023655502189334418, 1),
   'params_ftest': (5.1068887534926253, 0.025029428318314697, 180.0, 1.0),
   'ssr_chi2test': (5.192003566051107, 0.022691041876980185, 1),
   'ssr_ftest': (5.1068887534928926, 0.02502942831831103, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (6.0590602863881031, 0.048338344891521466, 2),
   'params_ftest': (2.9958935508767572, 0.05253365363635995, 177.0, 2.0),
   'ssr_chi2test': (6.161046624402025, 0.04593521190129396, 2),
   'ssr_ftest': (2.9958935508768088, 0.052533653636356793, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (7.2272499976750169, 0.064996666465984995, 3),
   'params_ftest': (2.3627726788513201, 0.072937873322380331, 174.0, 3.0),
   'ssr_chi2test': (7.3734802564150659, 0.060899969166285567, 3),
   'ssr_ftest': (2.3627726788512367, 0.072937873322388741, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.

In [20]:
x = np.asarray([approvals_array, truncated_df["Sadness Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0015  , p=0.9690  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=0.0015  , p=0.9687  , df=1
likelihood ratio test: chi2=0.0015  , p=0.9687  , df=1
parameter F test:         F=0.0015  , p=0.9690  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.4794  , p=0.6199  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=0.9860  , p=0.6108  , df=2
likelihood ratio test: chi2=0.9833  , p=0.6116  , df=2
parameter F test:         F=0.4794  , p=0.6199  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3434  , p=0.7940  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=1.0717  , p=0.7839  , df=3
likelihood ratio test: chi2=1.0685  , p=0.7847  , df=3
parameter F test:         F=0.3434  , p=0.7940  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.4573  , p=0.7670  

{1: ({'lrtest': (0.0015349379341387248, 0.96874824722991792, 1),
   'params_ftest': (0.0015097813486738695, 0.96904833412972025, 180.0, 1.0),
   'ssr_chi2test': (0.0015349443713035995, 0.96874818173229704, 1),
   'ssr_ftest': (0.0015097813488232127, 0.96904833412808233, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.9833100576038305, 0.61161331842325373, 2),
   'params_ftest': (0.47944202154260385, 0.61993042652862296, 177.0, 2.0),
   'ssr_chi2test': (0.98597116294659171, 0.61080007583959828, 2),
   'ssr_ftest': (0.47944202154271087, 0.61993042652856156, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (1.0685109558776276, 0.78468058004073127, 3),
   'params_ftest': (0.34340841300318253, 0.79396179761218399, 174.0, 3.0),
   'ssr_chi2test': (1.0716710819583268, 0.78391681909994804, 3),
   'ssr_ftest': (0.34340841300322072, 0.7939617976121558, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,

In [21]:
x = np.asarray([approvals_array, truncated_df["Joy Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=3.5868  , p=0.0598  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=3.6466  , p=0.0562  , df=1
likelihood ratio test: chi2=3.6107  , p=0.0574  , df=1
parameter F test:         F=3.5868  , p=0.0598  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.4170  , p=0.0921  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=4.9705  , p=0.0833  , df=2
likelihood ratio test: chi2=4.9039  , p=0.0861  , df=2
parameter F test:         F=2.4170  , p=0.0921  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.6840  , p=0.1722  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=5.2552  , p=0.1540  , df=3
likelihood ratio test: chi2=5.1804  , p=0.1591  , df=3
parameter F test:         F=1.6840  , p=0.1722  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.3225  , p=0.2635  

{1: ({'lrtest': (3.6107317596639632, 0.05740785447862598, 1),
   'params_ftest': (3.5868083268050373, 0.059843951738882094, 180.0, 1.0),
   'ssr_chi2test': (3.6465884655851966, 0.056184185006843794, 1),
   'ssr_ftest': (3.586808326805111, 0.05984395173887868, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (4.9038752819116098, 0.086126542399953501, 2),
   'params_ftest': (2.4169926625647848, 0.09212796755240206, 177.0, 2.0),
   'ssr_chi2test': (4.9705385829015682, 0.083303118673646356, 2),
   'ssr_ftest': (2.4169926625647733, 0.09212796755240206, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (5.1803934457789182, 0.15905449852421852, 3),
   'params_ftest': (1.6839994647667222, 0.17221581588111953, 174.0, 3.0),
   'ssr_chi2test': (5.2552397090135967, 0.15403332978050149, 3),
   'ssr_ftest': (1.683999464766788, 0.17221581588110396, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.

In [22]:
x = np.asarray([approvals_array, truncated_df["Fear Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.5052  , p=0.2215  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=1.5303  , p=0.2161  , df=1
likelihood ratio test: chi2=1.5239  , p=0.2170  , df=1
parameter F test:         F=1.5052  , p=0.2215  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.1373  , p=0.3230  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=2.3388  , p=0.3106  , df=2
likelihood ratio test: chi2=2.3239  , p=0.3129  , df=2
parameter F test:         F=1.1373  , p=0.3230  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.9455  , p=0.4199  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=2.9507  , p=0.3993  , df=3
likelihood ratio test: chi2=2.9269  , p=0.4030  , df=3
parameter F test:         F=0.9455  , p=0.4199  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.4483  , p=0.7735  

{1: ({'lrtest': (1.5239495161474679, 0.21702279072955222, 1),
   'params_ftest': (1.5052254910244443, 0.22147140655455097, 180.0, 1.0),
   'ssr_chi2test': (1.5303125825416717, 0.21606553773908821, 1),
   'ssr_ftest': (1.5052254910245952, 0.22147140655452704, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (2.3238788087039666, 0.31287879359427007, 2),
   'params_ftest': (1.1372631500869574, 0.32302744441355319, 177.0, 2.0),
   'ssr_chi2test': (2.3387784555462856, 0.3105565626751951, 2),
   'ssr_ftest': (1.1372631500870676, 0.32302744441351827, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (2.9268778719617785, 0.40303711416090282, 3),
   'params_ftest': (0.94551876426086157, 0.41993381537449992, 174.0, 3.0),
   'ssr_chi2test': (2.9506706264004725, 0.39929349464559416, 3),
   'ssr_ftest': (0.94551876426092485, 0.41993381537446806, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,

In [23]:
x = np.asarray([approvals_array, truncated_df["Disgust Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=4.3017  , p=0.0395  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=4.3733  , p=0.0365  , df=1
likelihood ratio test: chi2=4.3219  , p=0.0376  , df=1
parameter F test:         F=4.3017  , p=0.0395  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.6187  , p=0.0757  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=5.3854  , p=0.0677  , df=2
likelihood ratio test: chi2=5.3073  , p=0.0704  , df=2
parameter F test:         F=2.6187  , p=0.0757  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.0255  , p=0.1121  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=6.3211  , p=0.0970  , df=3
likelihood ratio test: chi2=6.2132  , p=0.1017  , df=3
parameter F test:         F=2.0255  , p=0.1121  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.8195  , p=0.1272  

{1: ({'lrtest': (4.3219088208536505, 0.037624694074991548, 1),
   'params_ftest': (4.3016539721147833, 0.039498704092138411, 180.0, 1.0),
   'ssr_chi2test': (4.3733482049833512, 0.036505195739126237, 1),
   'ssr_ftest': (4.3016539721147717, 0.039498704092138688, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (5.3072503403907376, 0.070395554072234481, 2),
   'params_ftest': (2.6187196846948826, 0.075719210459241612, 177.0, 2.0),
   'ssr_chi2test': (5.3853896340620313, 0.067698258916015455, 2),
   'ssr_ftest': (2.6187196846949989, 0.075719210459233285, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (6.2132265951408954, 0.10168477513795164, 3),
   'params_ftest': (2.0255454614654358, 0.11209729299146817, 174.0, 3.0),
   'ssr_chi2test': (6.3210987676767827, 0.096991323017705786, 3),
   'ssr_ftest': (2.0255454614654882, 0.11209729299145947, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  

In [24]:
x = np.asarray([approvals_array, truncated_df["Anger Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.3141  , p=0.5759  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=0.3193  , p=0.5720  , df=1
likelihood ratio test: chi2=0.3191  , p=0.5722  , df=1
parameter F test:         F=0.3141  , p=0.5759  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3058  , p=0.7369  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=0.6289  , p=0.7302  , df=2
likelihood ratio test: chi2=0.6278  , p=0.7306  , df=2
parameter F test:         F=0.3058  , p=0.7369  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.4182  , p=0.7402  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=1.3050  , p=0.7279  , df=3
likelihood ratio test: chi2=1.3003  , p=0.7290  , df=3
parameter F test:         F=0.4182  , p=0.7402  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.8783  , p=0.4782  

{1: ({'lrtest': (0.31905867496732299, 0.57217389667730179, 1),
   'params_ftest': (0.31410194212133857, 0.57587080702608451, 180.0, 1.0),
   'ssr_chi2test': (0.31933697449017995, 0.57200637166753154, 1),
   'ssr_ftest': (0.31410194212148845, 0.57587080702599935, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.62777463357724628, 0.730601350027549, 2),
   'params_ftest': (0.30579112003290432, 0.73692877087260911, 177.0, 2.0),
   'ssr_chi2test': (0.62885857453115346, 0.7302054929465267, 2),
   'ssr_ftest': (0.3057911200330059, 0.7369287708725365, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (1.3003498953216877, 0.72904999183161334, 3),
   'params_ftest': (0.41818708915788383, 0.74016965967525583, 174.0, 3.0),
   'ssr_chi2test': (1.3050321230617203, 0.72793849702622238, 3),
   'ssr_ftest': (0.41818708915789932, 0.74016965967525128, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0., 