In [1]:
from pandas import read_csv
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import grangercausalitytests
from numpy import log
import numpy as np
import pandas as pd
import datetime as datetime

def zscore(df, col):
    col_mean = df[col].rolling(window=10).mean()
    col_std = df[col].rolling(window=10).std()
    return (df[col] - col_mean)/col_std

df = pd.read_csv('./data/11-26/daily_plutchik_threshold_5.csv', parse_dates=['month/day'])
approval_rating_df = pd.read_csv('./data/approval_polllist.csv', parse_dates=["enddate"])

df["Anticipation Z-Score"] = zscore(df, "Anticipation")
df["Trust Z-Score"] = zscore(df, "Trust")
df["Surprise Z-Score"] = zscore(df, "Surprise")
df["Sadness Z-Score"] = zscore(df, "Sadness")
df["Joy Z-Score"] = zscore(df, "Joy")
df["Fear Z-Score"] = zscore(df, "Fear")
df["Disgust Z-Score"] = zscore(df, "Disgust")
df["Anger Z-Score"] = zscore(df, "Anger")

start_date = datetime.datetime(2017, 5, 15, 0, 0)
end_date = datetime.datetime(2017, 11, 17, 0, 0)

truncated_df = df[(df["month/day"] > start_date) & (df["month/day"] < end_date)]

In [2]:
result = adfuller(truncated_df["Anticipation Z-Score"])

In [3]:
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -10.834944
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [4]:
result = adfuller(truncated_df["Trust Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -11.206516
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [5]:
result = adfuller(truncated_df["Surprise Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -4.910347
p-value: 0.000033
	1%: -3.469
	5%: -2.878
	10%: -2.576


In [6]:
result = adfuller(truncated_df["Sadness Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -6.986860
p-value: 0.000000
	1%: -3.469
	5%: -2.878
	10%: -2.576


In [7]:
result = adfuller(truncated_df["Joy Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -10.037230
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [8]:
result = adfuller(truncated_df["Fear Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -10.320696
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [9]:
result = adfuller(truncated_df["Disgust Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -9.453887
p-value: 0.000000
	1%: -3.467
	5%: -2.877
	10%: -2.575


In [10]:
result = adfuller(truncated_df["Anger Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -6.304853
p-value: 0.000000
	1%: -3.467
	5%: -2.878
	10%: -2.575


In [11]:
# p-value is <= 0.05 and ADF Statistic is < values at 1%, 5%, and 10%

In [12]:
truncated_approvals = approval_rating_df.loc[approval_rating_df['pollster'] == 'Gallup']
truncated_approvals = truncated_approvals.loc[truncated_approvals['subgroup'] == 'All polls']
truncated_approvals = truncated_approvals[(truncated_approvals['enddate'] > start_date) & (truncated_approvals['enddate'] <= end_date)]
truncated_approvals = truncated_approvals['adjusted_approve']

approvals_array = truncated_approvals.values

In [13]:
x = np.asarray([approvals_array, truncated_df["Anticipation Z-Score"]]).T

In [14]:
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.5758  , p=0.2110  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=1.6020  , p=0.2056  , df=1
likelihood ratio test: chi2=1.5951  , p=0.2066  , df=1
parameter F test:         F=1.5758  , p=0.2110  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.8651  , p=0.4228  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=1.7791  , p=0.4108  , df=2
likelihood ratio test: chi2=1.7704  , p=0.4126  , df=2
parameter F test:         F=0.8651  , p=0.4228  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.2997  , p=0.2762  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=4.0558  , p=0.2555  , df=3
likelihood ratio test: chi2=4.0110  , p=0.2603  , df=3
parameter F test:         F=1.2997  , p=0.2762  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.9199  , p=0.4537  

{1: ({'lrtest': (1.5950673607435419, 0.20660364075863655, 1),
   'params_ftest': (1.5757761410925162, 0.21099735985176998, 180.0, 1.0),
   'ssr_chi2test': (1.6020390767775392, 0.20561448305465505, 1),
   'ssr_ftest': (1.5757761410926618, 0.21099735985174825, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (1.7704303206500072, 0.412625383115796, 2),
   'params_ftest': (0.86509691603690508, 0.42278307247211733, 177.0, 2.0),
   'ssr_chi2test': (1.7790693640532471, 0.41084688271962733, 2),
   'ssr_ftest': (0.86509691603688121, 0.42278307247212987, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (4.0110411955740801, 0.26027434588274456, 3),
   'params_ftest': (1.2996532820418842, 0.27619402077304284, 174.0, 3.0),
   'ssr_chi2test': (4.0558145525792453, 0.25549989805984735, 3),
   'ssr_ftest': (1.2996532820419679, 0.27619402077301353, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0., 

In [15]:
x = np.asarray([approvals_array, truncated_df["Trust Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.5792  , p=0.4476  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=0.5889  , p=0.4428  , df=1
likelihood ratio test: chi2=0.5879  , p=0.4432  , df=1
parameter F test:         F=0.5792  , p=0.4476  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3370  , p=0.7144  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=0.6930  , p=0.7072  , df=2
likelihood ratio test: chi2=0.6917  , p=0.7076  , df=2
parameter F test:         F=0.3370  , p=0.7144  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.7745  , p=0.5097  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=2.4169  , p=0.4905  , df=3
likelihood ratio test: chi2=2.4009  , p=0.4935  , df=3
parameter F test:         F=0.7745  , p=0.5097  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.7551  , p=0.5559  

{1: ({'lrtest': (0.58794748930176866, 0.44321391120372389, 1),
   'params_ftest': (0.57923900520794736, 0.44760665959177726, 180.0, 1.0),
   'ssr_chi2test': (0.58889298862828587, 0.44284751268431544, 1),
   'ssr_ftest': (0.57923900520815008, 0.44760665959169854, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.69169692769514768, 0.70761970895037896, 2),
   'params_ftest': (0.33698709201112198, 0.71437508001710848, 177.0, 2.0),
   'ssr_chi2test': (0.69301300278006683, 0.70715422178691667, 2),
   'ssr_ftest': (0.33698709201118632, 0.71437508001706618, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (2.4009380883773019, 0.49346002174420689, 3),
   'params_ftest': (0.77448674586759447, 0.50971188988327043, 174.0, 3.0),
   'ssr_chi2test': (2.4169327758972141, 0.49049037548454144, 3),
   'ssr_ftest': (0.77448674586761546, 0.50971188988325156, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0., 

In [16]:
x = np.asarray([approvals_array, truncated_df["Surprise Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=3.9177  , p=0.0493  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=3.9830  , p=0.0460  , df=1
likelihood ratio test: chi2=3.9403  , p=0.0471  , df=1
parameter F test:         F=3.9177  , p=0.0493  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.3287  , p=0.1004  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=4.7889  , p=0.0912  , df=2
likelihood ratio test: chi2=4.7270  , p=0.0941  , df=2
parameter F test:         F=2.3287  , p=0.1004  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.8839  , p=0.1341  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=5.8790  , p=0.1176  , df=3
likelihood ratio test: chi2=5.7856  , p=0.1225  , df=3
parameter F test:         F=1.8839  , p=0.1341  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.7707  , p=0.1369  

{1: ({'lrtest': (3.9402859642266321, 0.04714276302837693, 1),
   'params_ftest': (3.9177171487593192, 0.049304380340212103, 180.0, 1.0),
   'ssr_chi2test': (3.9830124345719988, 0.045961295233680234, 1),
   'ssr_ftest': (3.9177171487593432, 0.04930438034021082, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (4.72696181821766, 0.094092126350258848, 2),
   'params_ftest': (2.3286595573071209, 0.10040431295756658, 177.0, 2.0),
   'ssr_chi2test': (4.7888818014678645, 0.091223667753049534, 2),
   'ssr_ftest': (2.328659557307176, 0.10040431295756015, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (5.7855649411510512, 0.12252201554319656, 3),
   'params_ftest': (1.8838862293414669, 0.13406356978503126, 174.0, 3.0),
   'ssr_chi2test': (5.8790242674277424, 0.11764661211084687, 3),
   'ssr_ftest': (1.8838862293414866, 0.13406356978503048, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,

In [17]:
x = np.asarray([approvals_array, truncated_df["Sadness Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0665  , p=0.7968  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=0.0676  , p=0.7949  , df=1
likelihood ratio test: chi2=0.0676  , p=0.7949  , df=1
parameter F test:         F=0.0665  , p=0.7968  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0275  , p=0.9729  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=0.0565  , p=0.9721  , df=2
likelihood ratio test: chi2=0.0565  , p=0.9721  , df=2
parameter F test:         F=0.0275  , p=0.9729  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2057  , p=0.8924  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=0.6418  , p=0.8868  , df=3
likelihood ratio test: chi2=0.6406  , p=0.8871  , df=3
parameter F test:         F=0.2057  , p=0.8924  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.0742  , p=0.9899  

{1: ({'lrtest': (0.067585836125090282, 0.79488478542923802, 1),
   'params_ftest': (0.066490148963474188, 0.79681196499096574, 180.0, 1.0),
   'ssr_chi2test': (0.067598318113051711, 0.79486626852006503, 1),
   'ssr_ftest': (0.066490148963657417, 0.7968119649907266, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.056509730009338455, 0.97214057061423131, 2),
   'params_ftest': (0.027482898852895832, 0.97289547072442972, 177.0, 2.0),
   'ssr_chi2test': (0.056518503855730498, 0.97213630591756672, 2),
   'ssr_ftest': (0.027482898852923893, 0.97289547072440108, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (0.64064756082109398, 0.88706719361106467, 3),
   'params_ftest': (0.20565411917885468, 0.89238338044188381, 174.0, 3.0),
   'ssr_chi2test': (0.64178268226503865, 0.88680403586941114, 3),
   'ssr_ftest': (0.20565411917885215, 0.89238338044188381, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 

In [18]:
x = np.asarray([approvals_array, truncated_df["Joy Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.1775  , p=0.2793  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=1.1971  , p=0.2739  , df=1
likelihood ratio test: chi2=1.1932  , p=0.2747  , df=1
parameter F test:         F=1.1775  , p=0.2793  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7439  , p=0.4767  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=1.5299  , p=0.4654  , df=2
likelihood ratio test: chi2=1.5235  , p=0.4668  , df=2
parameter F test:         F=0.7439  , p=0.4767  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6041  , p=0.6131  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=1.8853  , p=0.5965  , df=3
likelihood ratio test: chi2=1.8756  , p=0.5986  , df=3
parameter F test:         F=0.6041  , p=0.6131  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.3634  , p=0.8344  

{1: ({'lrtest': (1.1932401184316177, 0.27467695899534927, 1),
   'params_ftest': (1.177513585124635, 0.27931395257743952, 180.0, 1.0),
   'ssr_chi2test': (1.1971388115435, 0.27389428848280611, 1),
   'ssr_ftest': (1.177513585124754, 0.27931395257741709, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (1.5235134088713949, 0.46684559651253299, 2),
   'params_ftest': (0.74393871623022445, 0.47671839827007978, 177.0, 2.0),
   'ssr_chi2test': (1.5299078684055845, 0.46535536744655193, 2),
   'ssr_ftest': (0.74393871623018804, 0.47671839827008922, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (1.8755931644316206, 0.59862474970813495, 3),
   'params_ftest': (0.60414358472331475, 0.6131476416001056, 174.0, 3.0),
   'ssr_chi2test': (1.8853446350848351, 0.59654134097995271, 3),
   'ssr_ftest': (0.60414358472331731, 0.6131476416001056, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  1.

In [19]:
x = np.asarray([approvals_array, truncated_df["Fear Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=4.8530  , p=0.0289  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=4.9339  , p=0.0263  , df=1
likelihood ratio test: chi2=4.8685  , p=0.0274  , df=1
parameter F test:         F=4.8530  , p=0.0289  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.7998  , p=0.0635  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=5.7578  , p=0.0562  , df=2
likelihood ratio test: chi2=5.6686  , p=0.0588  , df=2
parameter F test:         F=2.7998  , p=0.0635  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.8820  , p=0.1344  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=5.8732  , p=0.1179  , df=3
likelihood ratio test: chi2=5.7799  , p=0.1228  , df=3
parameter F test:         F=1.8820  , p=0.1344  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.5787  , p=0.1821  

{1: ({'lrtest': (4.8685142610138428, 0.027351038773237933, 1),
   'params_ftest': (4.8529702996235553, 0.028868323948991064, 180.0, 1.0),
   'ssr_chi2test': (4.9338531379506909, 0.026335533157307928, 1),
   'ssr_ftest': (4.8529702996236299, 0.02886832394898985, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (5.6686081750428912, 0.058759403010541347, 2),
   'params_ftest': (2.7998140382433272, 0.06351757811951847, 177.0, 2.0),
   'ssr_chi2test': (5.7578096605682454, 0.056196273602615053, 2),
   'ssr_ftest': (2.7998140382433507, 0.063517578119516471, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (5.7799045660051434, 0.12282339740462328, 3),
   'params_ftest': (1.8820135223740537, 0.13438008277612604, 174.0, 3.0),
   'ssr_chi2test': (5.8731801301672037, 0.11794597355216131, 3),
   'ssr_ftest': (1.8820135223740211, 0.13438008277613134, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,

In [20]:
x = np.asarray([approvals_array, truncated_df["Disgust Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=2.8303  , p=0.0942  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=2.8775  , p=0.0898  , df=1
likelihood ratio test: chi2=2.8551  , p=0.0911  , df=1
parameter F test:         F=2.8303  , p=0.0942  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.7271  , p=0.1808  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=3.5518  , p=0.1693  , df=2
likelihood ratio test: chi2=3.5175  , p=0.1723  , df=2
parameter F test:         F=1.7271  , p=0.1808  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.2061  , p=0.3091  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=3.7638  , p=0.2881  , df=3
likelihood ratio test: chi2=3.7252  , p=0.2927  , df=3
parameter F test:         F=1.2061  , p=0.3091  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.4044  , p=0.2345  

{1: ({'lrtest': (2.8550749504414625, 0.091085994223338768, 1),
   'params_ftest': (2.8302914333047156, 0.094235462494578773, 180.0, 1.0),
   'ssr_chi2test': (2.8774629571930208, 0.089827447603013519, 1),
   'ssr_ftest': (2.8302914333046103, 0.094235462494583533, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (3.5175429816248425, 0.17225635240016404, 2),
   'params_ftest': (1.7270897005879113, 0.18078377181497238, 177.0, 2.0),
   'ssr_chi2test': (3.5517550904747233, 0.169334785344851, 2),
   'ssr_ftest': (1.7270897005879833, 0.18078377181496286, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (3.7252152689404738, 0.29270550285872993, 3),
   'params_ftest': (1.2060842069307414, 0.30910056466558938, 174.0, 3.0),
   'ssr_chi2test': (3.763814507835519, 0.28812325928691396, 3),
   'ssr_ftest': (1.2060842069307187, 0.30910056466559949, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,

In [21]:
x = np.asarray([approvals_array, truncated_df["Anger Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.3072  , p=0.5801  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=0.3123  , p=0.5763  , df=1
likelihood ratio test: chi2=0.3120  , p=0.5764  , df=1
parameter F test:         F=0.3072  , p=0.5801  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3025  , p=0.7393  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=0.6221  , p=0.7327  , df=2
likelihood ratio test: chi2=0.6210  , p=0.7331  , df=2
parameter F test:         F=0.3025  , p=0.7393  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2993  , p=0.8259  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=0.9339  , p=0.8172  , df=3
likelihood ratio test: chi2=0.9315  , p=0.8178  , df=3
parameter F test:         F=0.2993  , p=0.8259  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.0068  , p=0.4055  

{1: ({'lrtest': (0.31202423292882031, 0.57644068347026511, 1),
   'params_ftest': (0.30717087807445626, 0.58010937229791315, 180.0, 1.0),
   'ssr_chi2test': (0.31229039270906045, 0.57627809802999708, 1),
   'ssr_ftest': (0.30717087807448568, 0.5801093722978885, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.62104182692633003, 0.73306499332372055, 2),
   'params_ftest': (0.30250594881424386, 0.73934537022357727, 177.0, 2.0),
   'ssr_chi2test': (0.62210262919993853, 0.73267627791457046, 2),
   'ssr_ftest': (0.30250594881425585, 0.73934537022356273, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (0.93153781774276467, 0.81781110173792826, 3),
   'params_ftest': (0.29927329313773904, 0.82589171459881927, 174.0, 3.0),
   'ssr_chi2test': (0.93393906996445331, 0.81723075687490143, 3),
   'ssr_ftest': (0.29927329313778067, 0.82589171459879107, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,