In [1]:
from pandas import read_csv
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import grangercausalitytests
from numpy import log
import numpy as np
import pandas as pd
import datetime as datetime

def zscore(df, col):
    col_mean = df[col].rolling(window=10).mean()
    col_std = df[col].rolling(window=10).std()
    return (df[col] - col_mean)/col_std

df = pd.read_csv('./data/11-26/daily_plutchik_threshold_5.csv', parse_dates=['month/day'])
approval_rating_df = pd.read_csv('./data/approval_polllist.csv', parse_dates=["enddate"])

df["Anticipation Z-Score"] = zscore(df, "Anticipation")
df["Trust Z-Score"] = zscore(df, "Trust")
df["Surprise Z-Score"] = zscore(df, "Surprise")
df["Sadness Z-Score"] = zscore(df, "Sadness")
df["Joy Z-Score"] = zscore(df, "Joy")
df["Fear Z-Score"] = zscore(df, "Fear")
df["Disgust Z-Score"] = zscore(df, "Disgust")
df["Anger Z-Score"] = zscore(df, "Anger")

start_date = datetime.datetime(2017, 7, 12, 0, 0)
end_date = datetime.datetime(2017, 12, 30, 0, 0)

truncated_df = df[(df["month/day"] > start_date) & (df["month/day"] < end_date)]

In [2]:
result = adfuller(truncated_df["Anticipation Z-Score"])

In [3]:
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -11.223374
p-value: 0.000000
	1%: -3.470
	5%: -2.879
	10%: -2.576


In [4]:
result = adfuller(truncated_df["Trust Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -11.209159
p-value: 0.000000
	1%: -3.470
	5%: -2.879
	10%: -2.576


In [5]:
result = adfuller(truncated_df["Surprise Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -4.064497
p-value: 0.001108
	1%: -3.472
	5%: -2.880
	10%: -2.576


In [6]:
result = adfuller(truncated_df["Sadness Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -6.111281
p-value: 0.000000
	1%: -3.472
	5%: -2.880
	10%: -2.577


In [7]:
result = adfuller(truncated_df["Joy Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -9.832941
p-value: 0.000000
	1%: -3.470
	5%: -2.879
	10%: -2.576


In [8]:
result = adfuller(truncated_df["Fear Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -10.120069
p-value: 0.000000
	1%: -3.470
	5%: -2.879
	10%: -2.576


In [9]:
result = adfuller(truncated_df["Disgust Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -10.212216
p-value: 0.000000
	1%: -3.470
	5%: -2.879
	10%: -2.576


In [10]:
result = adfuller(truncated_df["Anger Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -6.302642
p-value: 0.000000
	1%: -3.470
	5%: -2.879
	10%: -2.576


In [11]:
# p-value is <= 0.05 and ADF Statistic is < values at 1%, 5%, and 10%

In [16]:
truncated_approvals = approval_rating_df.loc[approval_rating_df['pollster'] == 'Ipsos']
truncated_approvals = truncated_approvals.loc[truncated_approvals['subgroup'] == 'All polls']
truncated_approvals = truncated_approvals[(truncated_approvals['enddate'] > start_date) & (truncated_approvals['enddate'] < end_date)]
truncated_approvals = truncated_approvals['adjusted_approve']

approvals_array = truncated_approvals.values

In [17]:
x = np.asarray([approvals_array, truncated_df["Anticipation Z-Score"]]).T
print(x)

[[  4.13517300e+01   2.04274616e+00]
 [  4.22517300e+01   4.39929563e-01]
 [  4.09517300e+01   5.69220709e-01]
 [  4.09517300e+01  -1.59566057e-01]
 [  3.84517300e+01  -7.02904306e-01]
 [  3.83517300e+01  -1.22413465e+00]
 [  3.90517300e+01  -1.41823872e+00]
 [  3.90517300e+01  -9.55528033e-01]
 [  3.87517300e+01  -3.69311103e-01]
 [  3.75517300e+01  -3.44851529e-01]
 [  3.70517300e+01   1.93459990e-01]
 [  3.58517300e+01   1.32698901e-01]
 [  3.59517300e+01   1.25049533e+00]
 [  3.64517300e+01  -7.86817016e-01]
 [  3.84517300e+01   2.25590571e+00]
 [  3.73517300e+01   9.25569310e-01]
 [  3.75517300e+01   8.19719592e-02]
 [  3.77517300e+01   1.03067153e+00]
 [  3.78517300e+01  -5.48073576e-01]
 [  3.78517300e+01   1.61570865e-01]
 [  3.82517300e+01  -1.12045804e+00]
 [  3.76517300e+01   1.97261340e+00]
 [  3.65517300e+01   2.20342530e+00]
 [  3.57517300e+01  -3.08164756e-01]
 [  3.52517300e+01  -6.24280255e-01]
 [  3.71517300e+01  -8.84892088e-01]
 [  3.80517300e+01  -2.68033111e-01]
 

In [18]:
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.1264  , p=0.7227  , df_denom=166, df_num=1
ssr based chi2 test:   chi2=0.1287  , p=0.7198  , df=1
likelihood ratio test: chi2=0.1286  , p=0.7199  , df=1
parameter F test:         F=0.1264  , p=0.7227  , df_denom=166, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2613  , p=0.7704  , df_denom=163, df_num=2
ssr based chi2 test:   chi2=0.5386  , p=0.7639  , df=2
likelihood ratio test: chi2=0.5377  , p=0.7642  , df=2
parameter F test:         F=0.2613  , p=0.7704  , df_denom=163, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2681  , p=0.8484  , df_denom=160, df_num=3
ssr based chi2 test:   chi2=0.8394  , p=0.8400  , df=3
likelihood ratio test: chi2=0.8373  , p=0.8405  , df=3
parameter F test:         F=0.2681  , p=0.8484  , df_denom=160, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2576  , p=0.9047  

{1: ({'lrtest': (0.1286225555751912, 0.71986451718450195, 1),
   'params_ftest': (0.12638740431922466, 0.72265884711939965, 166.0, 1.0),
   'ssr_chi2test': (0.1286715140357014, 0.71981345462475255, 1),
   'ssr_ftest': (0.12638740431909132, 0.72265884711951611, 166.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.53774928842284453, 0.76423905143274962, 2),
   'params_ftest': (0.26129038026849599, 0.77037919627656115, 163.0, 2.0),
   'ssr_chi2test': (0.5386108452159869, 0.76390990465932607, 2),
   'ssr_ftest': (0.26129038026846979, 0.77037919627658225, 163.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (0.83726425742884203, 0.84053470296814714, 3),
   'params_ftest': (0.26806119154109903, 0.84835004956448068, 160.0, 3.0),
   'ssr_chi2test': (0.83936660601328572, 0.84002971551970995, 3),
   'ssr_ftest': (0.26806119154116909, 0.84835004956443361, 160.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  

In [19]:
x = np.asarray([approvals_array, truncated_df["Trust Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=4.4506  , p=0.0364  , df_denom=166, df_num=1
ssr based chi2 test:   chi2=4.5310  , p=0.0333  , df=1
likelihood ratio test: chi2=4.4714  , p=0.0345  , df=1
parameter F test:         F=4.4506  , p=0.0364  , df_denom=166, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.5012  , p=0.0851  , df_denom=163, df_num=2
ssr based chi2 test:   chi2=5.1558  , p=0.0759  , df=2
likelihood ratio test: chi2=5.0782  , p=0.0789  , df=2
parameter F test:         F=2.5012  , p=0.0851  , df_denom=163, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.6326  , p=0.1839  , df_denom=160, df_num=3
ssr based chi2 test:   chi2=5.1121  , p=0.1638  , df=3
likelihood ratio test: chi2=5.0354  , p=0.1692  , df=3
parameter F test:         F=1.6326  , p=0.1839  , df_denom=160, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.1371  , p=0.0787  

{1: ({'lrtest': (4.4713512354960017, 0.034467723246723571, 1),
   'params_ftest': (4.4505947677253141, 0.036388640813692807, 166.0, 1.0),
   'ssr_chi2test': (4.5310272032864995, 0.033285632722273473, 1),
   'ssr_ftest': (4.4505947677252005, 0.036388640813694785, 166.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (5.0782281603741239, 0.078936300055267458, 2),
   'params_ftest': (2.5011566860452485, 0.085132602492235601, 163.0, 2.0),
   'ssr_chi2test': (5.1557585675530602, 0.075934869697426688, 2),
   'ssr_ftest': (2.501156686045086, 0.085132602492248424, 163.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (5.0353898773475407, 0.16922399004827648, 3),
   'params_ftest': (1.6325979316324657, 0.18394781918855102, 160.0, 3.0),
   'ssr_chi2test': (5.1120722734245563, 0.16377221609759562, 3),
   'ssr_ftest': (1.6325979316325929, 0.18394781918852421, 160.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.

In [20]:
x = np.asarray([approvals_array, truncated_df["Surprise Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=2.2388  , p=0.1365  , df_denom=166, df_num=1
ssr based chi2 test:   chi2=2.2792  , p=0.1311  , df=1
likelihood ratio test: chi2=2.2640  , p=0.1324  , df=1
parameter F test:         F=2.2388  , p=0.1365  , df_denom=166, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.6375  , p=0.1976  , df_denom=163, df_num=2
ssr based chi2 test:   chi2=3.3755  , p=0.1849  , df=2
likelihood ratio test: chi2=3.3421  , p=0.1881  , df=2
parameter F test:         F=1.6375  , p=0.1976  , df_denom=163, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.0228  , p=0.3841  , df_denom=160, df_num=3
ssr based chi2 test:   chi2=3.2028  , p=0.3614  , df=3
likelihood ratio test: chi2=3.1724  , p=0.3658  , df=3
parameter F test:         F=1.0228  , p=0.3841  , df_denom=160, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.8610  , p=0.1200  

{1: ({'lrtest': (2.263988297540493, 0.13241265885067008, 1),
   'params_ftest': (2.2387613242553561, 0.13648758437627589, 166.0, 1.0),
   'ssr_chi2test': (2.2792208662598621, 0.13111772745492062, 1),
   'ssr_ftest': (2.2387613242552491, 0.13648758437628541, 166.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (3.3420531518269172, 0.1880539148942966, 2),
   'params_ftest': (1.6375274486030285, 0.19764285451500585, 163.0, 2.0),
   'ssr_chi2test': (3.3755167038689895, 0.18493361577761966, 2),
   'ssr_ftest': (1.6375274486031111, 0.19764285451499133, 163.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (3.172439446013243, 0.36579489054276731, 3),
   'params_ftest': (1.022838806779816, 0.38414376379810911, 160.0, 3.0),
   'ssr_chi2test': (3.2027640137296531, 0.36140696821928608, 3),
   'ssr_ftest': (1.0228388067799292, 0.38414376379805687, 160.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  1.,

In [17]:
x = np.asarray([approvals_array, truncated_df["Sadness Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0665  , p=0.7968  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=0.0676  , p=0.7949  , df=1
likelihood ratio test: chi2=0.0676  , p=0.7949  , df=1
parameter F test:         F=0.0665  , p=0.7968  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0275  , p=0.9729  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=0.0565  , p=0.9721  , df=2
likelihood ratio test: chi2=0.0565  , p=0.9721  , df=2
parameter F test:         F=0.0275  , p=0.9729  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2057  , p=0.8924  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=0.6418  , p=0.8868  , df=3
likelihood ratio test: chi2=0.6406  , p=0.8871  , df=3
parameter F test:         F=0.2057  , p=0.8924  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.0742  , p=0.9899  

{1: ({'lrtest': (0.067585836125090282, 0.79488478542923802, 1),
   'params_ftest': (0.066490148963474188, 0.79681196499096574, 180.0, 1.0),
   'ssr_chi2test': (0.067598318113051711, 0.79486626852006503, 1),
   'ssr_ftest': (0.066490148963657417, 0.7968119649907266, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.056509730009338455, 0.97214057061423131, 2),
   'params_ftest': (0.027482898852895832, 0.97289547072442972, 177.0, 2.0),
   'ssr_chi2test': (0.056518503855730498, 0.97213630591756672, 2),
   'ssr_ftest': (0.027482898852923893, 0.97289547072440108, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (0.64064756082109398, 0.88706719361106467, 3),
   'params_ftest': (0.20565411917885468, 0.89238338044188381, 174.0, 3.0),
   'ssr_chi2test': (0.64178268226503865, 0.88680403586941114, 3),
   'ssr_ftest': (0.20565411917885215, 0.89238338044188381, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 

In [18]:
x = np.asarray([approvals_array, truncated_df["Joy Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.1775  , p=0.2793  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=1.1971  , p=0.2739  , df=1
likelihood ratio test: chi2=1.1932  , p=0.2747  , df=1
parameter F test:         F=1.1775  , p=0.2793  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7439  , p=0.4767  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=1.5299  , p=0.4654  , df=2
likelihood ratio test: chi2=1.5235  , p=0.4668  , df=2
parameter F test:         F=0.7439  , p=0.4767  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6041  , p=0.6131  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=1.8853  , p=0.5965  , df=3
likelihood ratio test: chi2=1.8756  , p=0.5986  , df=3
parameter F test:         F=0.6041  , p=0.6131  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.3634  , p=0.8344  

{1: ({'lrtest': (1.1932401184316177, 0.27467695899534927, 1),
   'params_ftest': (1.177513585124635, 0.27931395257743952, 180.0, 1.0),
   'ssr_chi2test': (1.1971388115435, 0.27389428848280611, 1),
   'ssr_ftest': (1.177513585124754, 0.27931395257741709, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (1.5235134088713949, 0.46684559651253299, 2),
   'params_ftest': (0.74393871623022445, 0.47671839827007978, 177.0, 2.0),
   'ssr_chi2test': (1.5299078684055845, 0.46535536744655193, 2),
   'ssr_ftest': (0.74393871623018804, 0.47671839827008922, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (1.8755931644316206, 0.59862474970813495, 3),
   'params_ftest': (0.60414358472331475, 0.6131476416001056, 174.0, 3.0),
   'ssr_chi2test': (1.8853446350848351, 0.59654134097995271, 3),
   'ssr_ftest': (0.60414358472331731, 0.6131476416001056, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  1.

In [19]:
x = np.asarray([approvals_array, truncated_df["Fear Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=4.8530  , p=0.0289  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=4.9339  , p=0.0263  , df=1
likelihood ratio test: chi2=4.8685  , p=0.0274  , df=1
parameter F test:         F=4.8530  , p=0.0289  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.7998  , p=0.0635  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=5.7578  , p=0.0562  , df=2
likelihood ratio test: chi2=5.6686  , p=0.0588  , df=2
parameter F test:         F=2.7998  , p=0.0635  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.8820  , p=0.1344  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=5.8732  , p=0.1179  , df=3
likelihood ratio test: chi2=5.7799  , p=0.1228  , df=3
parameter F test:         F=1.8820  , p=0.1344  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.5787  , p=0.1821  

{1: ({'lrtest': (4.8685142610138428, 0.027351038773237933, 1),
   'params_ftest': (4.8529702996235553, 0.028868323948991064, 180.0, 1.0),
   'ssr_chi2test': (4.9338531379506909, 0.026335533157307928, 1),
   'ssr_ftest': (4.8529702996236299, 0.02886832394898985, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (5.6686081750428912, 0.058759403010541347, 2),
   'params_ftest': (2.7998140382433272, 0.06351757811951847, 177.0, 2.0),
   'ssr_chi2test': (5.7578096605682454, 0.056196273602615053, 2),
   'ssr_ftest': (2.7998140382433507, 0.063517578119516471, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (5.7799045660051434, 0.12282339740462328, 3),
   'params_ftest': (1.8820135223740537, 0.13438008277612604, 174.0, 3.0),
   'ssr_chi2test': (5.8731801301672037, 0.11794597355216131, 3),
   'ssr_ftest': (1.8820135223740211, 0.13438008277613134, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,

In [20]:
x = np.asarray([approvals_array, truncated_df["Disgust Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=2.8303  , p=0.0942  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=2.8775  , p=0.0898  , df=1
likelihood ratio test: chi2=2.8551  , p=0.0911  , df=1
parameter F test:         F=2.8303  , p=0.0942  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.7271  , p=0.1808  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=3.5518  , p=0.1693  , df=2
likelihood ratio test: chi2=3.5175  , p=0.1723  , df=2
parameter F test:         F=1.7271  , p=0.1808  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.2061  , p=0.3091  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=3.7638  , p=0.2881  , df=3
likelihood ratio test: chi2=3.7252  , p=0.2927  , df=3
parameter F test:         F=1.2061  , p=0.3091  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.4044  , p=0.2345  

{1: ({'lrtest': (2.8550749504414625, 0.091085994223338768, 1),
   'params_ftest': (2.8302914333047156, 0.094235462494578773, 180.0, 1.0),
   'ssr_chi2test': (2.8774629571930208, 0.089827447603013519, 1),
   'ssr_ftest': (2.8302914333046103, 0.094235462494583533, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (3.5175429816248425, 0.17225635240016404, 2),
   'params_ftest': (1.7270897005879113, 0.18078377181497238, 177.0, 2.0),
   'ssr_chi2test': (3.5517550904747233, 0.169334785344851, 2),
   'ssr_ftest': (1.7270897005879833, 0.18078377181496286, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (3.7252152689404738, 0.29270550285872993, 3),
   'params_ftest': (1.2060842069307414, 0.30910056466558938, 174.0, 3.0),
   'ssr_chi2test': (3.763814507835519, 0.28812325928691396, 3),
   'ssr_ftest': (1.2060842069307187, 0.30910056466559949, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,

In [21]:
x = np.asarray([approvals_array, truncated_df["Anger Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.3072  , p=0.5801  , df_denom=180, df_num=1
ssr based chi2 test:   chi2=0.3123  , p=0.5763  , df=1
likelihood ratio test: chi2=0.3120  , p=0.5764  , df=1
parameter F test:         F=0.3072  , p=0.5801  , df_denom=180, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3025  , p=0.7393  , df_denom=177, df_num=2
ssr based chi2 test:   chi2=0.6221  , p=0.7327  , df=2
likelihood ratio test: chi2=0.6210  , p=0.7331  , df=2
parameter F test:         F=0.3025  , p=0.7393  , df_denom=177, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2993  , p=0.8259  , df_denom=174, df_num=3
ssr based chi2 test:   chi2=0.9339  , p=0.8172  , df=3
likelihood ratio test: chi2=0.9315  , p=0.8178  , df=3
parameter F test:         F=0.2993  , p=0.8259  , df_denom=174, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.0068  , p=0.4055  

{1: ({'lrtest': (0.31202423292882031, 0.57644068347026511, 1),
   'params_ftest': (0.30717087807445626, 0.58010937229791315, 180.0, 1.0),
   'ssr_chi2test': (0.31229039270906045, 0.57627809802999708, 1),
   'ssr_ftest': (0.30717087807448568, 0.5801093722978885, 180.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.62104182692633003, 0.73306499332372055, 2),
   'params_ftest': (0.30250594881424386, 0.73934537022357727, 177.0, 2.0),
   'ssr_chi2test': (0.62210262919993853, 0.73267627791457046, 2),
   'ssr_ftest': (0.30250594881425585, 0.73934537022356273, 177.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (0.93153781774276467, 0.81781110173792826, 3),
   'params_ftest': (0.29927329313773904, 0.82589171459881927, 174.0, 3.0),
   'ssr_chi2test': (0.93393906996445331, 0.81723075687490143, 3),
   'ssr_ftest': (0.29927329313778067, 0.82589171459879107, 174.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,