In [107]:
from pandas import read_csv
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.stattools import grangercausalitytests
from numpy import log
import numpy as np
import pandas as pd
import datetime as datetime

def zscore(df, col):
    col_mean = df[col].rolling(window=10).mean()
    col_std = df[col].rolling(window=10).std()
    return (df[col] - col_mean)/col_std

df = pd.read_csv('./data/11-26/daily_plutchik_threshold_5.csv', parse_dates=['month/day'])
approval_rating_df = pd.read_csv('./data/approval_polllist.csv', parse_dates=["enddate"])

df["Anticipation Z-Score"] = zscore(df, "Anticipation")
df["Trust Z-Score"] = zscore(df, "Trust")
df["Surprise Z-Score"] = zscore(df, "Surprise")
df["Sadness Z-Score"] = zscore(df, "Sadness")
df["Joy Z-Score"] = zscore(df, "Joy")
df["Fear Z-Score"] = zscore(df, "Fear")
df["Disgust Z-Score"] = zscore(df, "Disgust")
df["Anger Z-Score"] = zscore(df, "Anger")

start_date = datetime.datetime(2017, 7, 12, 0, 0)
end_date = datetime.datetime(2017, 12, 31, 0, 0)

print(df.loc[df["month/day"] == start_date])
print(df.loc[df["month/day"] == end_date])
truncated_df = df[(df["month/day"] > start_date) & (df["month/day"] < end_date)]

    month/day     Anger   Disgust      Fear       Joy   Sadness  Surprise  \
65 2017-07-12  0.018519  0.019577  0.046032  0.107407  0.039683  0.108466   

       Trust  Anticipation  Anticipation Z-Score  Trust Z-Score  \
65  0.653439      0.006878              0.473652       0.483474   

    Surprise Z-Score  Sadness Z-Score  Joy Z-Score  Fear Z-Score  \
65          -0.44768          1.35789    -0.306094     -0.503186   

    Disgust Z-Score  Anger Z-Score  
65        -0.757019      -0.243437  
     month/day     Anger   Disgust      Fear       Joy  Sadness  Surprise  \
237 2017-12-31  0.028192  0.018242  0.053897  0.199005   0.0199  0.090381   

       Trust  Anticipation  Anticipation Z-Score  Trust Z-Score  \
237  0.58126      0.009121              1.375677       0.194085   

     Surprise Z-Score  Sadness Z-Score  Joy Z-Score  Fear Z-Score  \
237         -0.941501        -0.355413     0.082123       0.54227   

     Disgust Z-Score  Anger Z-Score  
237        -0.042744      -0.636

In [81]:
result = adfuller(truncated_df["Anticipation Z-Score"])

In [82]:
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -11.237331
p-value: 0.000000
	1%: -3.469
	5%: -2.879
	10%: -2.576


In [83]:
result = adfuller(truncated_df["Trust Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -5.965600
p-value: 0.000000
	1%: -3.470
	5%: -2.879
	10%: -2.576


In [84]:
result = adfuller(truncated_df["Surprise Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -4.260156
p-value: 0.000520
	1%: -3.472
	5%: -2.880
	10%: -2.576


In [85]:
result = adfuller(truncated_df["Sadness Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -5.984463
p-value: 0.000000
	1%: -3.472
	5%: -2.880
	10%: -2.576


In [86]:
result = adfuller(truncated_df["Joy Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -9.792160
p-value: 0.000000
	1%: -3.469
	5%: -2.879
	10%: -2.576


In [87]:
result = adfuller(truncated_df["Fear Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -10.062988
p-value: 0.000000
	1%: -3.469
	5%: -2.879
	10%: -2.576


In [88]:
result = adfuller(truncated_df["Disgust Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -10.173978
p-value: 0.000000
	1%: -3.469
	5%: -2.879
	10%: -2.576


In [89]:
result = adfuller(truncated_df["Anger Z-Score"])
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])
for key, value in result[4].items():
	print('\t%s: %.3f' % (key, value))

ADF Statistic: -6.405567
p-value: 0.000000
	1%: -3.470
	5%: -2.879
	10%: -2.576


In [90]:
# p-value is <= 0.05 and ADF Statistic is < values at 1%, 5%, and 10%

In [108]:
truncated_approvals = approval_rating_df.loc[approval_rating_df['pollster'] == 'Ipsos']
truncated_approvals = truncated_approvals.loc[truncated_approvals['subgroup'] == 'All polls']
truncated_approvals = truncated_approvals[(truncated_approvals['enddate'] > start_date) & (truncated_approvals['enddate'] < end_date)]
truncated_approvals = truncated_approvals['adjusted_approve']

approvals_array = truncated_approvals.values

In [92]:
x = np.asarray([approvals_array, truncated_df["Anticipation Z-Score"]]).T
print(x)

[[  4.13517300e+01   2.04274616e+00]
 [  4.22517300e+01   4.39929563e-01]
 [  4.09517300e+01   5.69220709e-01]
 [  4.09517300e+01  -1.59566057e-01]
 [  3.84517300e+01  -7.02904306e-01]
 [  3.83517300e+01  -1.22413465e+00]
 [  3.90517300e+01  -1.41823872e+00]
 [  3.90517300e+01  -9.55528033e-01]
 [  3.87517300e+01  -3.69311103e-01]
 [  3.75517300e+01  -3.44851529e-01]
 [  3.70517300e+01   1.93459990e-01]
 [  3.58517300e+01   1.32698901e-01]
 [  3.59517300e+01   1.25049533e+00]
 [  3.64517300e+01  -7.86817016e-01]
 [  3.84517300e+01   2.25590571e+00]
 [  3.73517300e+01   9.25569310e-01]
 [  3.75517300e+01   8.19719592e-02]
 [  3.77517300e+01   1.03067153e+00]
 [  3.78517300e+01  -5.48073576e-01]
 [  3.78517300e+01   1.61570865e-01]
 [  3.82517300e+01  -1.12045804e+00]
 [  3.76517300e+01   1.97261340e+00]
 [  3.65517300e+01   2.20342530e+00]
 [  3.57517300e+01  -3.08164756e-01]
 [  3.52517300e+01  -6.24280255e-01]
 [  3.71517300e+01  -8.84892088e-01]
 [  3.80517300e+01  -2.68033111e-01]
 

In [93]:
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.1857  , p=0.6671  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=0.1891  , p=0.6637  , df=1
likelihood ratio test: chi2=0.1890  , p=0.6638  , df=1
parameter F test:         F=0.1857  , p=0.6671  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2920  , p=0.7471  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=0.6018  , p=0.7401  , df=2
likelihood ratio test: chi2=0.6008  , p=0.7405  , df=2
parameter F test:         F=0.2920  , p=0.7471  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2730  , p=0.8448  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=0.8545  , p=0.8364  , df=3
likelihood ratio test: chi2=0.8523  , p=0.8369  , df=3
parameter F test:         F=0.2730  , p=0.8448  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2938  , p=0.8817  

{1: ({'lrtest': (0.18895358159397802, 0.66378897307838769, 1),
   'params_ftest': (0.18572230189889591, 0.66705675038031509, 167.0, 1.0),
   'ssr_chi2test': (0.18905863067555045, 0.6637012685013588, 1),
   'ssr_ftest': (0.18572230189892308, 0.66705675038028378, 167.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.60075877696056068, 0.74053721609113232, 2),
   'params_ftest': (0.29201113532275585, 0.74714767373019697, 164.0, 2.0),
   'ssr_chi2test': (0.60182782767737386, 0.74014148594360951, 2),
   'ssr_ftest': (0.29201113532274942, 0.74714767373019697, 164.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (0.85233998543901635, 0.8369113006259804, 3),
   'params_ftest': (0.27296713047114884, 0.84483220822863703, 161.0, 3.0),
   'ssr_chi2test': (0.85450579973582153, 0.83639035194578915, 3),
   'ssr_ftest': (0.27296713047116522, 0.84483220822862404, 161.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0., 

In [94]:
x = np.asarray([approvals_array, truncated_df["Trust Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=4.7821  , p=0.0301  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=4.8680  , p=0.0274  , df=1
likelihood ratio test: chi2=4.7996  , p=0.0285  , df=1
parameter F test:         F=4.7821  , p=0.0301  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.5567  , p=0.0806  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=5.2694  , p=0.0717  , df=2
likelihood ratio test: chi2=5.1889  , p=0.0747  , df=2
parameter F test:         F=2.5567  , p=0.0806  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.6584  , p=0.1781  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=5.1914  , p=0.1583  , df=3
likelihood ratio test: chi2=5.1128  , p=0.1637  , df=3
parameter F test:         F=1.6584  , p=0.1781  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.1924  , p=0.0723  

{1: ({'lrtest': (4.7995741017123805, 0.028466773218143591, 1),
   'params_ftest': (4.78206359046606, 0.030148339921961642, 167.0, 1.0),
   'ssr_chi2test': (4.8679689244265365, 0.02735968374168506, 1),
   'ssr_ftest': (4.7820635904660689, 0.030148339921961642, 167.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (5.1889034058057177, 0.074686815414035643, 2),
   'params_ftest': (2.5567424860601631, 0.080645459341643286, 164.0, 2.0),
   'ssr_chi2test': (5.269383904197225, 0.071741065689788552, 2),
   'ssr_ftest': (2.5567424860601919, 0.080645459341641135, 164.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (5.1128406482081914, 0.16371843345127207, 3),
   'params_ftest': (1.6583756938317713, 0.17813232599288992, 161.0, 3.0),
   'ssr_chi2test': (5.1914369546036543, 0.15830404639396198, 3),
   'ssr_ftest': (1.6583756938317229, 0.17813232599290016, 161.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  

In [95]:
x = np.asarray([approvals_array, truncated_df["Surprise Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=2.4962  , p=0.1160  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=2.5410  , p=0.1109  , df=1
likelihood ratio test: chi2=2.5222  , p=0.1123  , df=1
parameter F test:         F=2.4962  , p=0.1160  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.7928  , p=0.1697  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=3.6949  , p=0.1576  , df=2
likelihood ratio test: chi2=3.6551  , p=0.1608  , df=2
parameter F test:         F=1.7928  , p=0.1697  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.1358  , p=0.3364  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=3.5556  , p=0.3136  , df=3
likelihood ratio test: chi2=3.5185  , p=0.3184  , df=3
parameter F test:         F=1.1358  , p=0.3364  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.8891  , p=0.1149  

{1: ({'lrtest': (2.5222175171114714, 0.11225263106782618, 1),
   'params_ftest': (2.4961793819207587, 0.11601505441465799, 167.0, 1.0),
   'ssr_chi2test': (2.5410209277039018, 0.11092304337789514, 1),
   'ssr_ftest': (2.4961793819208919, 0.116015054414647, 167.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (3.6551355836848529, 0.16080420182238842, 2),
   'params_ftest': (1.7928153782512886, 0.16973824924467909, 164.0, 2.0),
   'ssr_chi2test': (3.6949487673715096, 0.15763478897585545, 2),
   'ssr_ftest': (1.792815378251265, 0.16973824924468439, 164.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (3.5184653943591684, 0.3183751061982405, 3),
   'params_ftest': (1.1358064450415648, 0.33635278030680299, 161.0, 3.0),
   'ssr_chi2test': (3.555568001869017, 0.31362632844993377, 3),
   'ssr_ftest': (1.1358064450414915, 0.33635278030683069, 161.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,  1., 

In [96]:
x = np.asarray([approvals_array, truncated_df["Sadness Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.1970  , p=0.2755  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=1.2185  , p=0.2697  , df=1
likelihood ratio test: chi2=1.2141  , p=0.2705  , df=1
parameter F test:         F=1.1970  , p=0.2755  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3728  , p=0.6894  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=0.7682  , p=0.6810  , df=2
likelihood ratio test: chi2=0.7665  , p=0.6816  , df=2
parameter F test:         F=0.3728  , p=0.6894  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.1818  , p=0.9086  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=0.5691  , p=0.9035  , df=3
likelihood ratio test: chi2=0.5682  , p=0.9037  , df=3
parameter F test:         F=0.1818  , p=0.9086  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2294  , p=0.9215  

{1: ({'lrtest': (1.214135038601853, 0.27051473160587458, 1),
   'params_ftest': (1.196978430738586, 0.27550196104226277, 167.0, 1.0),
   'ssr_chi2test': (1.2184810372788748, 0.26965895515424748, 1),
   'ssr_ftest': (1.1969784307386595, 0.27550196104225921, 167.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.76650231024814275, 0.68164167998487946, 2),
   'params_ftest': (0.37275704745013255, 0.68941465772846611, 164.0, 2.0),
   'ssr_chi2test': (0.76824318315943341, 0.68104861236821557, 2),
   'ssr_ftest': (0.37275704745013927, 0.68941465772846611, 164.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (0.56817131684385913, 0.90367856591446205, 3),
   'params_ftest': (0.18180642950901335, 0.90863402114432845, 161.0, 3.0),
   'ssr_chi2test': (0.56913317063677848, 0.90346081438356063, 3),
   'ssr_ftest': (0.18180642950897091, 0.90863402114435265, 161.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,

In [97]:
x = np.asarray([approvals_array, truncated_df["Joy Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.2467  , p=0.6201  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=0.2511  , p=0.6163  , df=1
likelihood ratio test: chi2=0.2509  , p=0.6164  , df=1
parameter F test:         F=0.2467  , p=0.6201  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.2857  , p=0.2792  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=2.6499  , p=0.2658  , df=2
likelihood ratio test: chi2=2.6293  , p=0.2686  , df=2
parameter F test:         F=1.2857  , p=0.2792  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.2543  , p=0.2920  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=3.9266  , p=0.2695  , df=3
likelihood ratio test: chi2=3.8814  , p=0.2746  , df=3
parameter F test:         F=1.2543  , p=0.2920  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.3868  , p=0.2409  

{1: ({'lrtest': (0.2509394644770282, 0.61641434715878374, 1),
   'params_ftest': (0.24669314986020188, 0.62006639308236622, 167.0, 1.0),
   'ssr_chi2test': (0.2511247633306965, 0.61628420822787633, 1),
   'ssr_ftest': (0.24669314986015481, 0.62006639308239264, 167.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (2.6293237875134992, 0.26856511143123868, 2),
   'params_ftest': (1.2857425103541997, 0.2792168464974541, 164.0, 2.0),
   'ssr_chi2test': (2.6498839542664903, 0.26581838218604659, 2),
   'ssr_ftest': (1.2857425103541553, 0.27921684649746681, 164.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (3.8814191516717074, 0.27455669831302815, 3),
   'params_ftest': (1.2543318343187184, 0.29199160152831083, 161.0, 3.0),
   'ssr_chi2test': (3.9266040030845422, 0.26949941797193944, 3),
   'ssr_ftest': (1.2543318343186733, 0.29199160152833137, 161.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  0.,

In [98]:
x = np.asarray([approvals_array, truncated_df["Fear Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.5246  , p=0.4699  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=0.5340  , p=0.4649  , df=1
likelihood ratio test: chi2=0.5332  , p=0.4653  , df=1
parameter F test:         F=0.5246  , p=0.4699  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7854  , p=0.4577  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=1.6186  , p=0.4452  , df=2
likelihood ratio test: chi2=1.6109  , p=0.4469  , df=2
parameter F test:         F=0.7854  , p=0.4577  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.8374  , p=0.4752  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=2.6215  , p=0.4537  , df=3
likelihood ratio test: chi2=2.6013  , p=0.4573  , df=3
parameter F test:         F=0.8374  , p=0.4752  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.7494  , p=0.5598  

{1: ({'lrtest': (0.53316289964351427, 0.46528013782111455, 1),
   'params_ftest': (0.52457631445969177, 0.46990950096054651, 167.0, 1.0),
   'ssr_chi2test': (0.53399984106669962, 0.46493008053139495, 1),
   'ssr_ftest': (0.52457631445964015, 0.46990950096057016, 167.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (1.6109039734838007, 0.4468858944054549, 2),
   'params_ftest': (0.78535911210343334, 0.45766305824307973, 164.0, 2.0),
   'ssr_chi2test': (1.6186059749448312, 0.44516824595511706, 2),
   'ssr_ftest': (0.78535911210340914, 0.45766305824309239, 164.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (2.6012809602623292, 0.45726502225408516, 3),
   'params_ftest': (0.83743133622690247, 0.475181539744298, 161.0, 3.0),
   'ssr_chi2test': (2.6215241829710161, 0.45372856892215996, 3),
   'ssr_ftest': (0.8374313362268524, 0.47518153974432453, 161.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  0.,  

In [99]:
x = np.asarray([approvals_array, truncated_df["Disgust Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.3847  , p=0.5359  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=0.3916  , p=0.5315  , df=1
likelihood ratio test: chi2=0.3912  , p=0.5317  , df=1
parameter F test:         F=0.3847  , p=0.5359  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.1023  , p=0.9028  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=0.2109  , p=0.8999  , df=2
likelihood ratio test: chi2=0.2107  , p=0.9000  , df=2
parameter F test:         F=0.1023  , p=0.9028  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.9487  , p=0.4186  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=2.9699  , p=0.3963  , df=3
likelihood ratio test: chi2=2.9440  , p=0.4003  , df=3
parameter F test:         F=0.9487  , p=0.4186  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.6465  , p=0.6301  

{1: ({'lrtest': (0.39115310623458299, 0.53169390217742762, 1),
   'params_ftest': (0.38469280459874777, 0.53594780833233857, 167.0, 1.0),
   'ssr_chi2test': (0.39160345378330952, 0.53145776040493264, 1),
   'ssr_ftest': (0.38469280459889815, 0.5359478083322694, 167.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.21074611809916632, 0.89998871101821998, 2),
   'params_ftest': (0.10231929668998895, 0.90279884542320332, 164.0, 2.0),
   'ssr_chi2test': (0.21087757488531536, 0.89992955815049236, 2),
   'ssr_ftest': (0.10231929668991632, 0.90279884542326916, 164.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (2.9439715823095867, 0.40034457041613225, 3),
   'params_ftest': (0.94872363491272027, 0.41857986216288767, 161.0, 3.0),
   'ssr_chi2test': (2.9699174658136629, 0.39628660435782548, 3),
   'ssr_ftest': (0.94872363491269796, 0.41857986216289611, 161.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  

In [100]:
x = np.asarray([approvals_array, truncated_df["Anger Z-Score"]]).T
grangercausalitytests(x, maxlag=7)


Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.2293  , p=0.6327  , df_denom=167, df_num=1
ssr based chi2 test:   chi2=0.2334  , p=0.6290  , df=1
likelihood ratio test: chi2=0.2332  , p=0.6291  , df=1
parameter F test:         F=0.2293  , p=0.6327  , df_denom=167, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3846  , p=0.6813  , df_denom=164, df_num=2
ssr based chi2 test:   chi2=0.7927  , p=0.6728  , df=2
likelihood ratio test: chi2=0.7909  , p=0.6734  , df=2
parameter F test:         F=0.3846  , p=0.6813  , df_denom=164, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3522  , p=0.7876  , df_denom=161, df_num=3
ssr based chi2 test:   chi2=1.1024  , p=0.7765  , df=3
likelihood ratio test: chi2=1.0988  , p=0.7774  , df=3
parameter F test:         F=0.3522  , p=0.7876  , df_denom=161, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.6810  , p=0.6061  

{1: ({'lrtest': (0.23322249807705475, 0.62914462140481575, 1),
   'params_ftest': (0.22926403430225104, 0.63269639293304292, 167.0, 1.0),
   'ssr_chi2test': (0.23338254988855323, 0.62902698277722435, 1),
   'ssr_ftest': (0.22926403430228465, 0.63269639293302915, 167.0, 1)},
   array([[ 0.,  1.,  0.]])]),
 2: ({'lrtest': (0.79088298532315093, 0.67338268010106017, 2),
   'params_ftest': (0.38464135688730561, 0.68130715435964906, 164.0, 2.0),
   'ssr_chi2test': (0.79273645504806933, 0.67275892196947962, 2),
   'ssr_ftest': (0.38464135688722889, 0.68130715435969891, 164.0, 2)},
   array([[ 0.,  0.,  1.,  0.,  0.],
          [ 0.,  0.,  0.,  1.,  0.]])]),
 3: ({'lrtest': (1.0987965209600929, 0.77736461617353736, 3),
   'params_ftest': (0.35215481528228665, 0.78763895049116883, 161.0, 3.0),
   'ssr_chi2test': (1.102397682622855, 0.77649530523196786, 3),
   'ssr_ftest': (0.35215481528230091, 0.78763895049116006, 161.0, 3)},
   array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
          [ 0.,  0.,  